server:
  port: 8091
spring:
  application:
    name: fitness-main-service
  profiles:
    active: "dev"
  config:
    import: [optional:configserver:http://root:s3cr3t@localhost:8888, classpath:secret.yml]
